### ISSUE TITLE
Script Crashed

### ISSUE THREAD

**Issue by m7zr** [qpeckin/steam-trade-farm#1]
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\تجريبي\steam-trade-farm-main\steam-trade-farm-main\node_modules\chalk\source\index.js from D:\تجريبي\steam-trade-farm-main\steam-trade-farm-main\account1.js not supported.
Instead change the require of index.js in D:\تجريبي\steam-trade-farm-main\steam-trade-farm-main\account1.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\تجريبي\steam-trade-farm-main\steam-trade-farm-main\account1.js:5:15) {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}
Script Crashed

Waiting for 15 seconds, press a key to continue ...

**Comment by deepyes02** [comment]
Sounds like fun project.
